server:
  port: 8678
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000 # session cookie 30天过期

spring:
  application:
    name: chronicle
  session:
    store-type: redis
    timeout: 2592400 # session 30天过期
  profiles:
    active: local
  datasource:
    url: <your url>
    username: root
    password: <your password>
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # 连接在池中的最大存活时间（单位：毫秒）。
      # 比如设置为 25 分钟（1500000 毫秒），确保它小于数据库的 wait_timeout
      max-lifetime: 1500000
      # 空闲连接存活时间（建议小于 max-lifetime）
      idle-timeout: 600000
      # 连接验证超时时间
      validation-timeout: 3000
  data:
    redis:
      host: <your url>
      port: 6379
      password: <your password>
      database: 0
  elasticsearch:
    uris: <your url>:9200
    username: elastic
    password: <your password>
    connection-timeout: 5s
    socket-timeout: 10s

# Elasticsearch 索引配置
elasticsearch:
  index:
    entries: entries_index_local

# springdoc-openapi 配置
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.cxin.chronicle.controller
# knife4j 接口文档配置
knife4j:
  enable: true
  setting:
    language: zh_cn
